### ISSUE TITLE
Syntax for augmenting existing columns in select()

### ISSUE THREAD

**Issue by tdsmith** [mitre/sparklyr.nested#9]
This seems like a low-priority wishlist item but I'd like to be able to add extracted data as new column while persisting all existing columns -- something like `SELECT *, foo.bar as bar, ...`.

Maybe it would be nice if the dplyr selectors worked (`starts_with()`, `everything()`, etc).

**Comment by mattpollock** [comment]
I plan to spend some more time on this package 2nd half of this month. I think this might be a little tricky though due to nested fields being unknown to `colnames`. One easy thing might be to add a `.keep_all_top` or some such param so that when pulling out nested fields you don't need to explicitly list all top level fields that you want to keep (this annoys me also)

**Comment by mattpollock** [comment]
For posterity, I ended up using `dplyr::select_vars` with tidy evaluation stuff and some regex to pull out nested column references, so `starts_with`, `everything`, etc. are all supported as @tdsmith suggested.

The one regression is that on account of this I am a little less careful about column ordering, with nested fields that get promoted being to the far right of the resulting `data.frame`, even if they are present early in the call to `sdf_select`

**Comment by tdsmith** [comment]
Sorry for the slow reaction, but that's amazing; thank you!
